allowBuilds:
  '@editframe/cli': true
  node-av: true
minimumReleaseAgeExclude:
  - '@editframe/api@0.59.41'
  - '@editframe/assets@0.59.41'
  - '@editframe/cli@0.59.41'
  - '@editframe/dev-server@0.59.41'
  - '@editframe/elements@0.59.41'
  - '@editframe/react@0.59.41'
  - '@editframe/vite-plugin@0.59.41'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
