name: Publish Icon Set

on:
    push:
        branches: [master]
        paths: ['.github/workflows/publish-iconset.yml', 'assets/**', 'scripts/**', 'icons/**', 'Makefile']
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install packages
              run: |
                sudo apt-get install --yes \
                    inkscape \
                    imagemagick \
                    build-essential \
                    fonts-space-grotesk

            - name: Verify font installation
              run: |
                fc-list | grep "Space Grotesk" || exit 1

            - name: Build assets
              run: make
            - name: Upload artifacts
              uses: actions/upload-artifact@v6
              with:
                  name: icon-set
                  path: out/
    publish_release:
        name: "Publish on GitHub"
        needs: build
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: icon-set
                  path: ./icon-set
                  merge-multiple: true
            - name: Create Tag Name
              id: tag_name
              run: echo "tag_name=$(date +'v%Y.%m.%d-%H.%M')" >> $GITHUB_ENV
            - name: Prepare release assets
              run: |
                  mkdir -p ./upload/icons
                  mv ./icon-set/ICONSHEET.pdf ./upload/ICONSHEET.pdf
                  cd ./icon-set
                  zip -r ../upload/icons.zip ./*
            - name: Create tag
              uses: mathieudutour/github-tag-action@v6.2
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                custom_tag: ${{ env.tag_name }}
                tag_prefix: ''
            - name: Publish Release
              uses: softprops/action-gh-release@v3
              with:
                  working_directory: ./upload
                  tag_name: ${{ env.tag_name }}
                  body: Release of LuzTech Typography on ${{ github.event.repository.updated_at }}
                  files: |
                      ICONSHEET.pdf
                      icons.zip
    publish-onedrive:
        name: 'Publish on OneDrive'
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v6
              with:
                  name: icon-set
                  path: icon-set/
            - name: Publish to OneDrive
              run: echo "TODO!"
    publish-cdn:
        name: 'Publish on CDN'
        needs: build
        environment: Azure
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v6
              with:
                  name: icon-set
                  path: icon-set/
            - name: Azure Login
              uses: Azure/login@v3
              with:
                client-id: ${{ vars.CLIENT_ID }}
                tenant-id: ${{ vars.TENANT_ID }}
                subscription-id: ${{ vars.SUBSCRIPTION_ID }}
            - name: Prepare assets
              run: |
                  mkdir -p ./upload
                  rm -f ./icon-set/ICONSHEET.pdf
                  mv ./icon-set/* ./upload
            - name: Azure CLI Action
              uses: Azure/cli@v3
              with:
                inlineScript: |
                  az storage blob delete-batch \
                    --auth-mode login
                    --account-name ${{ vars.STORAGE_ACCOUNT_NAME }} \
                    -s assets \
                    --pattern 'icons/*'

                  az storage blob upload-batch \
                    --auth-mode login
                    --account-name ${{ vars.STORAGE_ACCOUNT_NAME }} \
                    -s ./upload \
                    -d assets \
                    --destination-path icons
                    --overwrite
