name: Publish to OneDrive

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install packages
              run: |
                sudo add-apt-repository ppa:inkscape.dev/stable
                sudo apt-get update
                sudo apt-get install --yes \
                    inkscape \
                    imagemagick \
                    build-essential \
                    fonts-space-grotesk \
                    fonts-liberation \
                    libasound2 \
                    libatk-bridge2.0-0 \
                    libatk1.0-0 \
                    libcups2 \
                    libdrm2 \
                    libgbm1 \
                    libsecret-1-dev \
                    libgtk-3-0 \
                    libnspr4 \
                    libnss3 \
                    libx11-xcb1 \
                    libxcomposite1 \
                    libxdamage1 \
                    libxrandr2 \
                    xdg-utils \
                    libu2f-udev \
                    libxshmfence1 \
                    libglu1-mesa \
                    chromium \
                    chromium-sandbox

            - name: Verify font installation
              run: |
                fc-list | grep "Space Grotesk" || exit 1

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '24'

            - name: Install IFMD
              run: npm install --global @giancarl021/ifmd

            - name: Build assets
              run: make
            - name: Upload artifacts
              uses: actions/upload-artifact@v6
              with:
                  name: icon-set
                  path: out/
    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v6
              with:
                  name: icon-set
                  path: icon-set/