name: Publish to OneDrive

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install packages
              run: |
                sudo add-apt-repository ppa:inkscape.dev/stable
                sudo apt-get update
                sudo apt-get install --yes \
                    inkscape \
                    imagemagick \
                    build-essential \
                    fonts-space-grotesk

            - name: Verify font installation
              run: |
                fc-list | grep "Space Grotesk" || exit 1

            - name: Build assets
              run: make
            - name: Upload artifacts
              uses: actions/upload-artifact@v6
              with:
                  name: icon-set
                  path: out/
    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v6
              with:
                  name: icon-set
                  path: icon-set/